config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'characters#index'

  resources :characters do
    resources :skills
    resources :items
    member do
      get 'items'
      get 'edit_stats'
      patch 'update_stats'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :skills
  has_many :items
  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true
  validates :total_hitpoints, presence: true
  validates :total_resource, presence: true
  validates :image, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character

  validates :name, presence: true
  validates :description, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :character

  validates :name, presence: true
  validates :casting_time, presence: true
  validates :range, presence: true
  validates :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
    @action_skills = @character.skills.where(casting_time: 'action')
    @bonus_action_skills = @character.skills.where(casting_time: 'bonus action')
    @reaction_skills = @character.skills.where(casting_time: 'reaction')
    @items = @character.items
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def edit_stats
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])

    if @character.update(character_params)
      redirect_to @character
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_stats
    if @character.update(character_stats_params)
      redirect_to @character, notice: 'Character stats were successfully updated.'
    else
      render :edit_stats, status: :unprocessable_entity
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to root_path, status: :see_other
  end

  def items
    @character = Character.find(params[:id])
  end

  private

  def character_params
    params.require(:character).permit(:name, :description, :image, :current_hitpoints,
                                      :total_hitpoints, :current_resource, :total_resource, :user_id)
  end

  def character_stats_params
    params.require(:character).permit(:current_hitpoints, :total_hitpoints, :current_resource, :total_resource)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_character

  def new
    @item = @character.items.build
  end

  def show
    @item = Item.find_by(id: params[:id])
    return unless @item.nil?

    redirect_to root_path, alert: 'Item not found'
  end

  def create
    @item = @character.items.build(item_params)

    if @item.save
      redirect_to items_character_path(@character), notice: 'Item was successfully created.'

    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to character_item_path(@character, @item), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to character_path(params[:character_id])
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def item_params
    params.require(:item).permit(:name, :description)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_character

  def new
    @skill = @character.skills.build
  end

  def show
    @skill = Skill.find_by(id: params[:id])
    return unless @skill.nil?

    redirect_to root_path, alert: 'Skill not found'
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def create
    @skill = @character.skills.build(skill_params)

    if @skill.save
      redirect_to @character, notice: 'Skill was successfully created.'
    else
      render :new
    end
  end

  def update
    @skill = Skill.find(params[:id])

    if @skill.update(skill_params)
      redirect_to character_skill_path(@character, @skill), notice: 'Skill was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    redirect_to character_path(params[:character_id])
  end

  private

  def set_character
    @character = Character.find(params[:character_id])
  end

  def skill_params
    params.require(:skill).permit(:name, :casting_time, :range, :target, :components, :duration, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
  def sorted_skills(character)
    character.skills.order(:casting_time)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/characters/_form.html.erb
<%= form_with model: @character do |form| %>
  <div class="skill">
  
    <div><%= form.label :name %></div>
    <div><%= form.text_field :name %>
    <% @character.errors.full_messages_for(:name).each do |message| %>
    <div class="error-message"><%= message %></div>
    <% end %>
  </div>

    <div><%= form.label :description %></div>
    <div><%= form.text_area :description %>
    <% @character.errors.full_messages_for(:description).each do |message| %>
    <div class="error-message"><%= message %></div>
    <% end %>
  </div>
    
    <div><%= form.label :current_hitpoints %></div>
    <div><%= form.text_field :current_hitpoints %>
  </div>
  
    <div><%= form.label :total_hitpoints %></div>
    <div><%= form.text_field :total_hitpoints %>
    <% @character.errors.full_messages_for(:total_hitpoints).each do |message| %>
    <div class="error-message"><%= message %></div>
    <% end %>
  </div>
    <div><%= form.label :current_resource %></div>
    <div><%= form.text_field :current_resource %>
  </div>
  
    <div><%= form.label :total_resource %></div>
    <div><%= form.text_field :total_resource %>
        <% @character.errors.full_messages_for(:total_resource).each do |message| %>
    <div class="error-message"><%= message %></div>
    <% end %>
  </div>

    <div><%= form.label :image %></div>
    <div><%= form.file_field :image %>
    <% @character.errors.full_messages_for(:image).each do |message| %>
    <div class="error-message"><%= message %></div>
    <% end %>
  </div>

  <div><%= form.number_field :user_id, value: current_user.id, type:"hidden" %></div>

  <div>
    <%= form.submit "Create", class: 'button-link'%>
    <%= link_to "Back", root_path, class: 'button-link', role: 'button' %>

  </div>
  </div>
<% end %>

app/views/characters/_form_stats.html.erb
<%= form_with model: @character do |form| %>
  <div class="skill">
  <div>
    <%= form.label :current_hitpoints %><br>
    <%= form.text_field :current_hitpoints %>
  </div>
  <div>
    <%= form.label :current_resource %><br>
    <%= form.text_field :current_resource %>
  </div>

  <div>
    <%= form.submit "Update", class: 'button-link'%>
  </div>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Edit Character</h1>

<%= render "form", character: @character %>

<%= link_to 'Back', character_path(@character), class: 'button-link', role: 'button' %>

app/views/characters/edit_stats.html.erb
<h1>Edit Stats</h1>

<%= render "form_stats", character: @character %>

<%= link_to 'Back', character_path(@character), class: 'button-link', role: 'button' %>

app/views/characters/index.html.erb
<h1>Characters</h1>

  <div class="con">
  <% @characters.each do |character| %>
    <div class="box">
      <div class='center-link'>
      <% if character.image.attached? %>
        <%= link_to character_path(character) do %>
          <%= image_tag character.image, width: 200, height: 200 %>
        <% end %>
      <% end %>
      <br><%= link_to character.name, character %>
      </div>
    </div>
  <% end %>
  </div>
<%= link_to "New Character", new_character_path, class: 'button-link', role: 'button' %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render "form", character: @character %>

app/views/characters/show.html.erb
<div class="box-container">
  <div class="box-left">
    <div class="box-left-inner-l">
    <h1><%= @character.name %></h1>
    <p><%= @character.description %></p>
    
    <div class="main-info">
      <p>Hitpoints <%= @character.current_hitpoints %>/<%= @character.total_hitpoints %></p>
      <p>Resource <%= @character.current_resource %>/<%= @character.total_resource %></p>
    </div>
    </div>
    <div class="box-left-inner-r">
    <%= image_tag @character.image, width: 200, height: 200 %>
    </div>
  </div>
  
  <div class="box-right">
    <% if current_user && current_user.id == @character.user_id %>
      <%= link_to "Edit Stats", edit_stats_character_path(@character), class: 'button-link', role: 'button' %>
    <% end %>
    <%= link_to "See inventory", items_character_path(@character), class: 'button-link', role: 'button' %>
  </div>
</div>
<% if current_user && current_user.id == @character.user_id %>
<%= link_to "Edit", edit_character_path(@character), class: 'button-link', role: 'button' %>
<%= link_to "Destroy", character_path(@character), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: 'button-link', role: 'button' %>
<% end %>
<div><h1>Skills</h1></div>

<div class="skills-container">
  <div class="skills-column">
    <h2>Action</h2>
    <%= render partial: 'skills/skill', collection: @action_skills, as: :skill, locals: { character: @character } %>
  </div>

  <div class="skills-column">
    <h2>Bonus Action</h2>
    <%= render partial: 'skills/skill', collection: @bonus_action_skills, as: :skill, locals: { character: @character } %>
  </div>

  <div class="skills-column">
    <h2>Reaction</h2>
    <%= render partial: 'skills/skill', collection: @reaction_skills, as: :skill, locals: { character: @character } %>
  </div>
</div>

<% if current_user && current_user.id == @character.user_id %>
  <%= link_to 'Add a skill', new_character_skill_path(@character), class: 'button-link', role: 'button' %>
<% end %>

app/views/items/_form.html.erb
<%= form_with(model: [@character, @item], local: true) do |form| %>
  <div class="skill">
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @item.errors.full_messages_for(:name).each do |message| %>
        <div class="error-message"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
      <% @item.errors.full_messages_for(:description).each do |message| %>
        <div class="error-message"><%= message %></div>
      <% end %>
    </div>

    <%= form.submit class: 'button-link' %>
  </div>
<% end %>

<%= link_to "Back", items_character_path(@character), class: 'button-link', role: 'button' %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render "form", item: @item %>

app/views/items/index.html.erb
<h2>Items</h2>
<% @character.items.each do |item| %>
    <div class="skill">
  <div>
    <strong>Name:</strong>
    <%= link_to item.name, character_item_path(character_id: @character.id, id: item.id) %>
  </div>

  <div>
    <strong>Description:</strong>
    <%= item.description %>
  </div>
  </div>

<% end %>

<% if current_user && current_user.id == @character.user_id %>
  <%= link_to 'Add item', new_character_item_path(@character), class: 'button-link', role: 'button' %>
<% end %>
<%= link_to 'Back', character_path(@character), class: 'button-link', role: 'button' %>

app/views/items/new.html.erb
<h1>New Item for <%= @character.name %></h1>

<%= render "form", item: @item %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<div class="skill">

<p><strong>Name:</strong> <%= @item.name %></p>
<p><strong>Description:</strong> <%= @item.description %></p>
</div>
<% if current_user && current_user.id == @character.user_id %>
<%= button_to "Delete", character_item_path(character_id: @character.id, id: @item.id), method: :delete, class: 'button-link button-delete', role: 'button' %>

<%= link_to 'Edit', edit_character_item_path(@character, @item), class: 'button-link', role: 'button' %>
<% end %>
<%= link_to 'Back', items_character_path(@character), class: 'button-link', role: 'button' %>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<div class="navbar">
  <div class="navbar-brand">
<%= link_to "Characters",root_path %>
  </div>


<div class="navbar-links">
    <% if user_signed_in? %>
      <div class="navbar-user">
        <%#= link_to "My Account", edit_user_registration_path, class:"nav-link"%>
        <%= link_to "Sign out", destroy_user_session_path,class:"nav-link", data: { turbo_method: :delete }%>
      <% else %>
        <div class="navbar-auth">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link "%>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnDManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/skills/_form.html.erb
<%= form_with(model: [@character, skill], local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="skill">
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, value: @skill.name %>
  </div>

  <div>
    <%= form.label :casting_time %><br>
    <%= form.select :casting_time, options_for_select([['Action', 'action'], ['Bonus Action', 'bonus action'], ['Reaction', 'reaction']]), value: @skill.casting_time %>
  </div>

  <div>
    <%= form.label :range %><br>
    <%= form.text_field :range, value: @skill.range %>
  </div>

  <div>
    <%= form.label :target %><br>
    <%= form.text_field :target, value: @skill.target %>
  </div>

  <div>
    <%= form.label :components %><br>
    <%= form.text_field :components, value: @skill.components %>
  </div>

  <div>
    <%= form.label :duration %><br>
    <%= form.text_field :duration, value: @skill.duration %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, value: @skill.description %>
  </div>

  <div>
    <%= form.submit class: 'button-link' %>
  </div>
</div>

<% end %>

<%= link_to 'Back', character_path(@character), class: 'button-link', role: 'button' %>

app/views/skills/_skill.html.erb
<div class="skill">
  <p>
    <strong>Name:</strong>
    <%= link_to skill.name, character_skill_path(character_id: @character.id, id: skill.id) %>
  </p>
  <p>
    <strong>Cast Time:</strong>
    <%= skill.casting_time %>
  </p>
  <p>
    <strong>Range:</strong>
    <%= skill.range %>
  </p>
  <p>
    <strong>Target:</strong>
    <%= skill.target %>
  </p>
  <p>
    <strong>Components:</strong>
    <%= skill.components %>
  </p>
  <p>
    <strong>Range:</strong>
    <%= skill.range %>
  </p>
  <p>
    <strong>Duration:</strong>
    <%= skill.duration %>
  </p>
</div>

app/views/skills/edit.html.erb
<h1>Edit skill</h1>

<%= render "form", skill: @skill %>

app/views/skills/new.html.erb
<h1>New Skill for <%= @character.name %></h1>

<%= render "form", skill: @skill %>

app/views/skills/show.html.erb
<h1><%= @skill.name %></h1>
<div class="skill">

<p><strong>Cast Time:</strong> <%= @skill.casting_time %></p>
<p><strong>Range:</strong> <%= @skill.range %></p>
<p><strong>Target:</strong> <%= @skill.target %></p>
<p><strong>Components:</strong> <%= @skill.components %></p>
<p><strong>Duration:</strong> <%= @skill.duration %></p>
<p><strong>Description:</strong> <%= @skill.description %></p>
</div>
<% if current_user && current_user.id == @character.user_id %>
<%= button_to "Delete", character_skill_path(character_id: @character.id, id: @skill.id), method: :delete, class: 'button-link button-delete', role: 'button' %>

<%= link_to 'Edit', edit_character_skill_path(@character, @skill), class: 'button-link', role: 'button' %>
<% end %>
<%= link_to 'Back', character_path(@character), class: 'button-link', role: 'button' %>